image: archlinux
packages:
    - nodejs
    - yarn
sources:
    - https://git.sr.ht/~siarune/src
secrets:
    - 1d4233ec-b94b-4b97-9b0e-06cb60ff182d
tasks:
    - setup: |
        mv src siarune
        cd siarune
        yarn install
        yarn add vercel
        yarn vercel pull --yes --environment=production -t pRjJDDbIhqiLi7vNRjkIqxYe
    - build: |
        cd siarune
        yarn vercel -t pRjJDDbIhqiLi7vNRjkIqxYe
    - deploy: |
        cd siarune
        yarn vercel --prod  -t pRjJDDbIhqiLi7vNRjkIqxYe
