image: alpine/latest
packages:
    - nodejs
    - npm
sources:
    - https://git.sr.ht/~siarune/siarune.dev
tasks:
    - setup: |
          sudo npm i -g pnpm
          mv siarune.dev siarune
          cd siarune
          pnpm install
          pnpm pullConfig
    - build: |
          cd siarune
          pnpm buildProd
    - deploy: |
          cd siarune
          pnpm run deploy
