image: archlinux
packages:
    - nodejs
    - yarn
sources:
    - https://git.sr.ht/~siarune/siarune.dev
tasks:
    - setup: |
        mv siarune.dev siarune
        cd siarune
        yarn install
        yarn pullConfig
    - build: |
        cd siarune
        yarn buildProd
    - deploy: |
        cd siarune
        yarn deploy
